### CS 5012: Foundations of Computer Science
#### Programming Assignment: Computing Edit Distance

Last Updated: March 21, 2022


---

**INSTRUCTIONS**

Recall that *edit distance* is used to quantify the dissimilarity of two strings.  
This is done by counting the minimum number of operations required to transform one string into the other.

The operations we will consider are:
- delete a character (**H**ello -> ello)
- insert a character (ello -> **H**ello)
- substitute a character (**t**op -> **b**op)

We apply a penalty of 1 for each of these operations.

Example:
- string1: Hello
- string2: elllo

edit_distance(Hello,elllo) = 2

Starting with *elllo* for example:   
elllo -> **H**elllo (insert H: +1)   
Hel**l**lo -> Hello (delete l: +1)

The strings now match after two operations.

Solve all tasks below, showing code and results.  
Submit your completed file.


**TOTAL POINTS: 10**

---

1) (6 POINTS) Write a function that take two strings as input, and computes and returns their edit distance. Use a matrix (as in LCS calculations) to track results, and have the function print the matrix.

In [ ]:
import numpy as np


# https://en.wikipedia.org/wiki/Wagner%E2%80%93Fischer_algorithm
def compute_edit_distance(string_1: str, string_2: str) -> int:
    length_of_string_1 = len(string_1)
    length_of_string_2 = len(string_2)

    number_of_rows = length_of_string_1 + 1
    number_of_columns = length_of_string_2 + 1
    matrix = np.zeros((number_of_rows, number_of_columns), dtype = int)

    matrix[:, 0] = np.arange(0, length_of_string_1 + 1)
    matrix[0, :] = np.arange(0, length_of_string_2 + 1)

    for i in range(1, length_of_string_1 + 1):
        for j in range(1, length_of_string_2 + 1):
            if string_1[i - 1] == string_2[j - 1]:
                penalty = 0
            else:
                penalty = 1
            matrix[i, j] = min(
                matrix[i - 1, j] + 1,
                matrix[i, j - 1] + 1,
                matrix[i - 1, j - 1] + penalty
            )

    print("raw matrix")
    print(matrix)

    print("\nannotated matrix")
    string_consisting_of_space_representing_empty_string_and_string_1 = ' ' + string_1
    string_consisting_of_space_representing_empty_string_and_string_2 = ' ' + string_2
    annotated_matrix = "  " + ' '.join(string_consisting_of_space_representing_empty_string_and_string_2)
    for i in range(0, length_of_string_1 + 1):
        annotated_matrix += '\n' + string_consisting_of_space_representing_empty_string_and_string_1[i] + ' ' + ' '.join(str(x) for x in matrix[i])
    print(annotated_matrix)

    edit_distance = matrix[length_of_string_1, length_of_string_2]

    return edit_distance

#string_1 = "sitting"
#string_2 = "kitten"

string_1 = "Hello"
string_2 = "elllo"

edit_distance = compute_edit_distance(string_1, string_2)
print(f"\nThe edit distance between strings \"{string_1}\" and \"{string_2}\" is {edit_distance}.")

raw matrix
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 1 2 3 4 5]
 [3 2 1 2 3 4]
 [4 3 2 1 2 3]
 [5 4 3 2 2 2]]

annotated matrix
    e l l l o
  0 1 2 3 4 5
H 1 1 2 3 4 5
e 2 1 2 3 4 5
l 3 2 1 2 3 4
l 4 3 2 1 2 3
o 5 4 3 2 2 2

The edit distance between strings "Hello" and "elllo" is 2.


2) (1 POINT) Compute edit distance between **Bellman** and empty string

In [ ]:
string_1 = "Bellman"
string_2 = ""

edit_distance = compute_edit_distance(string_1, string_2)
print(f"\nThe edit distance between strings \"{string_1}\" and \"{string_2}\" is {edit_distance}.")

raw matrix
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]

annotated matrix
   
  0
B 1
e 2
l 3
l 4
m 5
a 6
n 7

The edit distance between strings "Bellman" and "" is 7.


3)  (1 POINT) Compute edit distance between **test** and **test**

In [ ]:
string_1 = "test"
string_2 = "test"

edit_distance = compute_edit_distance(string_1, string_2)
print(f"\nThe edit distance between strings \"{string_1}\" and \"{string_2}\" is {edit_distance}.")

raw matrix
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 0 1]
 [4 3 2 1 0]]

annotated matrix
    t e s t
  0 1 2 3 4
t 1 0 1 2 3
e 2 1 0 1 2
s 3 2 1 0 1
t 4 3 2 1 0

The edit distance between strings "test" and "test" is 0.


4a)  (1 POINT) Compute edit distance between **mailman** and **namliam**

In [ ]:
string_1 = "mailman"
string_2 = "namliam"

edit_distance = compute_edit_distance(string_1, string_2)
print(f"\nThe edit distance between strings \"{string_1}\" and \"{string_2}\" is {edit_distance}.")

raw matrix
[[0 1 2 3 4 5 6 7]
 [1 1 2 2 3 4 5 6]
 [2 2 1 2 3 4 4 5]
 [3 3 2 2 3 3 4 5]
 [4 4 3 3 2 3 4 5]
 [5 5 4 3 3 3 4 4]
 [6 6 5 4 4 4 3 4]
 [7 6 6 5 5 5 4 4]]

annotated matrix
    n a m l i a m
  0 1 2 3 4 5 6 7
m 1 1 2 2 3 4 5 6
a 2 2 1 2 3 4 4 5
i 3 3 2 2 3 3 4 5
l 4 4 3 3 2 3 4 5
m 5 5 4 3 3 3 4 4
a 6 6 5 4 4 4 3 4
n 7 6 6 5 5 5 4 4

The edit distance between strings "mailman" and "namliam" is 4.


4b)  (1 POINT) Show each step of the process to change **mailman** to **namliam**.

This should verify the edit distance. You might find your solution from (4a) helpful.

Given that when we stack "mailman" and "namliam" there are 4 pairs of distinct characters and that the edit distance (the minimum number of operations required to transform one string into the other) between "mailman" and "namliam" is 4, we substitute 4 characters from left to right in "mailman" to generate "namliam". Changing characters in pairs of identical characters or deleting from and inserting into a string with 7 characters would contribute to more than 4 operations occurring. Following the diagonal of our matrix from bottom right to top left, first, we substitute 'm' for 'n' at position 6 in "namlian" to form "namliam". Second, we substitute 'i' for the 'm' at position 4 in "namlman" to form "namlian". Third, we substitute 'm' for 'i' at position 2 in "nailman" to form "namlman". Fourth, we substitute 'n' for the 'm' at position 0 in "mailman" and form "nailman".

A transition from a 4 at position (7, 7) in our matrix to a 3 at position (6, 6) represents a difference in characters 'n' and 'm' at position 6 in "mailman" and "namliam" and our transition from 'n' to 'm'. Moving diagonally from 3 and 3 represents that 'a' at position 5 is the same for both strings. A transition between 3 and 2 represents a difference in characters 'm' and 'i' at position 4 and our transition from 'm' to 'i'. Moving diagonally from 2 and 2 represents that 'l' at position 3 is the same for both strings. A transition between 2 and 1 represents a difference in characters 'i' and 'm' at position 2 and our transition from 'i' to 'm'. Moving diagonally from 1 and 1 represents that 'a' at position 1 is the same for both strings. A transition between 1 and 0 represents a difference in characters 'm' and 'n' at position 0 and our transition from 'm' to 'n'.